# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    inline: false
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: ['Smiley', 'Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            language: fr
    plugins:
        smiley:
            path: "/bundles/fosckeditor/plugins/smiley"
            filename: "smiley.js"
        